### PR TITLE
CI: Add initial version II

### PR DESCRIPTION
**Pull request by ubaidsk**

### CODE REVIEW

**Comment by ubaidsk** [comment]
It seems macOS and ubuntu pass. I think Ubuntu failed in first attempt but passed in the second run here https://github.com/lcompilers/lpython-conda-testing/actions/runs/6291440082/job/17079864280?pr=3.

**Comment by ubaidsk** [comment]
@certik Is this good to merge?

**Review by certik — APPROVED** [review]
Yes, go ahead and keep merging PRs here as you see fit, until we get it fully working.

**Comment by ubaidsk** [comment]
Only the windows test fails currently. I attempted setting up a virtual widows machine on my Mac, but it didn't succeed. I will attempt this again after the PyCon Event, this time on my linux machine.

For now, we atleast know that the LPython from conda seems to work on Linux and Mac systems.

**Comment by certik** [comment]
We'll do best effort o Windows. Linux and macOS are the most important, everything has to work there. Windows we'll iteratively improve

**Pull request merged**
