### PR TITLE
Allow CI to pass by not running tests on Windows

### PR DESCRIPTION
**Pull request by ubaidsk**

### CODE REVIEW

**Comment by certik** [comment]
The error message on macOS:
```
[ 24%] Built target loop_06
semantic error: String method not implemented: join
  --> /Users/runner/work/lpython-conda-testing/lpython-conda-testing/lpython/integration_tests/test_str_01.py:52:15
   |
[ 24%] Generating test_str_02.o
52 |     res:str = a.join(p)
[ 24%] Linking C executable if_03
   |               ^^^^^^^^^ 
```
Signals either mismatch of a test and a conda binary package, or a bug in lpython.

**Comment by certik** [comment]
The log says:
```
HEAD is now at 2293972e5 Merge pull request #2334 from Shaikh-Ubaid/changes_from_lf
```
Which is the correct commit for `v0.20.0`. So it should be the matching test.

**Comment by ubaidsk** [comment]
>Which is the correct commit for v0.20.0. So it should be the matching test.

Yes, it should be matching the test. But it seems it does not, which is probably why it fails.

**Comment by ubaidsk** [comment]
`str.join()` was added recently. Unsure why the integration tests corresponding to the latest main are getting executed at the CI.

**Comment by certik** [comment]
Something is wrong:
```
            git clone https://github.com/lcompilers/lpython.git
            git fetch https://github.com/lcompilers/lpython.git --tags -f
```
Shouldn't the second command be executed after `cd lpython`? I think you are checking out the tags into the root directory, which contains the `https://github.com/lcompilers/lpython-conda-testing` repository, then checking it out, all good. But then you cd to `lpython`, which has the latest main, so it is testing features that we don't have in conda yet.


Instead, the way it has to work is to `cd lpython` right after clone. Btw, there are flags you can pass to clone to get the tags, in fact they might be downloaded by default? Either way, do everything in that directory and `git checkout v0.20.0` I think is fine, that way it's each to change.

**Comment by ubaidsk** [comment]
>Either way, do everything in that directory and git checkout v0.20.0 I think is fine, that way it's each to change.

Yes, fixed it.

**Pull request merged**
